spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/house
    username: ${MY_DATABASE_USERNAME}
    password: ${MY_DATABASE_PASSWORD}
  config:
    import: classpath:oauth.yml
  redis:
    host: 127.0.0.1
    port: 6379

  servlet:
    multipart:
      max-file-size: 1GB


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      encoding: UTF-8

logging:
  level:
    org.hibernate.SQL: debug
    com.amazonaws.util.EC2MetadataUtils: error

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: house-image-bucket
    stack:
      auto: false
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
