spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.11.10.221:3306/house
    username: ${MY_DATABASE_USERNAME}
    password: ${MY_DATABASE_PASSWORD}
  config:
    import: classpath:oauth.yml, classpath:s3.yml
  redis:
    host: 127.0.0.1
    port: 6379

  servlet:
    multipart:
      max-file-size: 1GB


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      encoding: UTF-8

logging:
  level:
    org.hibernate.SQL: debug
    com.amazonaws.util.EC2MetadataUtils: error

